framework:
    default_locale: en
    enabled_locales: ['en','es']
    translator:
        default_path: '%kernel.project_dir%/translations'
        paths:
          - '%kernel.project_dir%/translations'
#          - '%kernel.project_dir%/automatic_translations'
        fallbacks:
            - en
#        providers:
#            crowdin:
#                dsn: '%env(CROWDIN_DSN)%'
#            loco:
#                dsn: '%env(LOCO_DSN)%'
#            lokalise:
#                dsn: '%env(LOKALISE_DSN)%'
