twig:
    form_themes: ['bootstrap_5_layout.html.twig']
    default_path: '%kernel.project_dir%/templates'

    # Used for app.* in Twig templates
    globals:
        config: '@App\Service\AppConfigService'

when@test:
    twig:
        strict_variables: true
