when@dev:
# see https://github.com/symfony/symfony/issues/45241 for an idea to disable the profiler
    web_profiler:
        toolbar: false
        intercept_redirects: false

    framework:
        profiler:
            only_exceptions: false
            collect_serializer_data: true

when@test:
    web_profiler:
        toolbar: false
        intercept_redirects: false

    framework:
        profiler: { collect: false }
