version: '2'
services:
  database:
    environment:
      MYSQL_DATABASE: member_directory
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    image: mysql:5.7
    ports: [3306]
    volumes:
      - member-directory-mysql-data:/var/lib/mysql

  mailer:
    image: 'schickling/mailcatcher'
    ports: [1025, 1080]

###> meilisearch/search-bundle ###
  meilisearch:
    image: getmeili/meilisearch:${MEILISEARCH_VERSION:-v1.0}
    environment:
      # You should definitely change the master key in production
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY:-!ChangeMe!}
    volumes:
      - meilisearch_data:/meili_data
###< meilisearch/search-bundle ###

volumes:
  member-directory-mysql-data:

###> meilisearch/search-bundle ###
  meilisearch_data:
###< meilisearch/search-bundle ###
