survos_crawler:
  resource:
    path: '@SurvosCrawlerBundle/src/Controller/'
    namespace: Survos\CrawlerBundle\Controller
  type: attribute
  # consider adding /admin to this route and securing it in security.yaml
  prefix: '/crawler'
